const languages = {
  en: {
    // 通用
    home: 'Home',
    allTools: 'All Tools',
    aboutUs: 'About Us',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    orLoginWith: 'Or login with',
    orSignupWith: 'Or sign up with',
    noAccount: 'No account?',
    haveAccount: 'Already have an account?',
    acceptTerms: 'I agree to the Terms of Service',
    sendMessage: 'Send Message',
    allRightsReserved: 'All rights reserved',
    
    // 首页
    heroTitle: 'Discover the Best AI Voice Tools',
    heroDesc: 'Find and compare the latest AI voice technology tools for speech synthesis, recognition, and more.',
    categories: 'Categories',
    speechSynthesis: 'Speech Synthesis',
    speechRecognition: 'Speech Recognition',
    audioEditing: 'Audio Editing',
    musicGeneration: 'Music Generation',
    voiceCloning: 'Voice Cloning',
    featuredTools: 'Featured Tools',
    newsletterTitle: 'Stay Updated',
    newsletterDesc: 'Subscribe to our newsletter for the latest AI voice tools and updates.',
    newsletterPlaceholder: 'Enter your email',
    subscribe: 'Subscribe',
    
    // 工具页
    searchPlaceholder: 'Search AI voice tools...',
    allCategories: 'All Categories',
    allPrices: 'All Prices',
    allRatings: 'All Ratings',
    free: 'Free',
    under10: 'Under $10',
    between10and50: '$10 - $50',
    over50: 'Over $50',
    stars: 'Stars',
    
    // 关于页
    ourStory: 'Our Story',
    storyContent: 'RecallLook was founded in 2024 with a vision to make AI voice technology accessible to everyone. We believe that voice technology has the power to transform how we communicate, create, and interact with the digital world.',
    ourMission: 'Our Mission',
    missionContent: 'Our mission is to help people discover and use the best AI voice tools for their needs. We curate and review the latest voice technology tools, making it easier for everyone to find the right solution.',
    ourTeam: 'Our Team',
    ceo: 'CEO & Founder',
    cto: 'Chief Technology Officer',
    productManager: 'Product Manager',
    contactUs: 'Contact Us',
    message: 'Message',
    quickLinks: 'Quick Links',
    
    // 页脚
    footerAbout: 'RecallLook is your trusted source for discovering and comparing AI voice tools. We help you find the perfect solution for your voice technology needs.',
    
    // 错误消息
    error: 'Error',
    success: 'Success',
    loading: 'Loading...',
    failedToLoad: 'Failed to load',
    messageSent: 'Message sent successfully!',
    failedToSend: 'Failed to send message',
    invalidEmail: 'Please enter a valid email address',
    invalidPassword: 'Password must be at least 6 characters',
    passwordsDontMatch: 'Passwords do not match',
    requiredField: 'This field is required'
  },
  zh: {
    // 通用
    home: '首页',
    allTools: '所有工具',
    aboutUs: '关于我们',
    login: '登录',
    signup: '注册',
    email: '邮箱',
    password: '密码',
    name: '姓名',
    rememberMe: '记住我',
    forgotPassword: '忘记密码?',
    orLoginWith: '或使用以下方式登录',
    orSignupWith: '或使用以下方式注册',
    noAccount: '还没有账号?',
    haveAccount: '已有账号?',
    acceptTerms: '我同意服务条款和隐私政策',
    sendMessage: '发送消息',
    allRightsReserved: '保留所有权利',
    
    // 首页
    heroTitle: '发现最佳AI语音工具',
    heroDesc: '查找和比较最新的AI语音技术工具,包括语音合成、识别等。',
    categories: '分类',
    speechSynthesis: '语音合成',
    speechRecognition: '语音识别',
    audioEditing: '音频编辑',
    musicGeneration: '音乐生成',
    voiceCloning: '语音克隆',
    featuredTools: '精选工具',
    newsletterTitle: '保持更新',
    newsletterDesc: '订阅我们的新闻通讯,获取最新的AI语音工具和更新。',
    newsletterPlaceholder: '输入您的邮箱',
    subscribe: '订阅',
    
    // 工具页
    searchPlaceholder: '搜索AI语音工具...',
    allCategories: '所有分类',
    allPrices: '所有价格',
    allRatings: '所有评分',
    free: '免费',
    under10: '10美元以下',
    between10and50: '10-50美元',
    over50: '50美元以上',
    stars: '星',
    
    // 关于页
    ourStory: '我们的故事',
    storyContent: 'RecallLook成立于2024年,愿景是让AI语音技术为每个人所用。我们相信语音技术有能力改变我们的交流、创作和与数字世界互动的方式。',
    ourMission: '我们的使命',
    missionContent: '我们的使命是帮助人们发现和使用最适合他们需求的AI语音工具。我们精心策划和审查最新的语音技术工具,让每个人都能更容易找到合适的解决方案。',
    ourTeam: '我们的团队',
    ceo: '首席执行官兼创始人',
    cto: '首席技术官',
    productManager: '产品经理',
    contactUs: '联系我们',
    message: '消息',
    quickLinks: '快速链接',
    
    // 页脚
    footerAbout: 'RecallLook是您发现和比较AI语音工具的可靠来源。我们帮助您找到最适合您语音技术需求的解决方案。',
    
    // 错误消息
    error: '错误',
    success: '成功',
    loading: '加载中...',
    failedToLoad: '加载失败',
    messageSent: '消息发送成功!',
    failedToSend: '消息发送失败',
    invalidEmail: '请输入有效的邮箱地址',
    invalidPassword: '密码至少需要6个字符',
    passwordsDontMatch: '密码不匹配',
    requiredField: '此字段为必填项'
  }
};
