const languages = {
  en: {
    // 通用
    home: 'Home',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    search: 'Search',
    filter: 'Filter',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    reset: 'Reset',
    close: 'Close',
    confirm: 'Confirm',
    cancel: 'Cancel',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',

    // 导航
    allTools: 'All Tools',
    aboutUs: 'About Us',
    contact: 'Contact',
    profile: 'Profile',
    favorites: 'Favorites',
    settings: 'Settings',

    // 首页
    heroTitle: 'Discover AI Voice Tools',
    heroSubtitle: 'Find the perfect voice tools for your needs',
    featuredTools: 'Featured Tools',
    popularCategories: 'Popular Categories',
    latestTools: 'Latest Tools',
    newsletterTitle: 'Stay Updated',
    newsletterSubtitle: 'Subscribe to our newsletter for the latest updates',
    subscribe: 'Subscribe',

    // 工具页面
    searchPlaceholder: 'Search tools...',
    categoryLabel: 'Category',
    priceLabel: 'Price',
    ratingLabel: 'Rating',
    sortBy: 'Sort By',
    noResults: 'No results found',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    free: 'Free',
    paid: 'Paid',
    low: 'Low',
    medium: 'Medium',
    high: 'High',

    // 关于页面
    aboutTitle: 'About RecallLook',
    aboutSubtitle: 'Your trusted source for AI voice tools',
    ourStory: 'Our Story',
    ourMission: 'Our Mission',
    ourTeam: 'Our Team',
    contactUs: 'Contact Us',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    send: 'Send',

    // 表单验证
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPassword: 'Password must be at least 8 characters long',
    passwordMismatch: 'Passwords do not match',
    acceptTerms: 'Please accept the terms and conditions',

    // 错误消息
    networkError: 'Network error, please try again',
    serverError: 'Server error, please try again later',
    invalidCredentials: 'Invalid email or password',
    emailExists: 'Email already exists',
    invalidToken: 'Invalid or expired token',
    unauthorized: 'Unauthorized access'
  },

  zh: {
    // 通用
    home: '首页',
    login: '登录',
    signup: '注册',
    logout: '退出',
    search: '搜索',
    filter: '筛选',
    loading: '加载中...',
    error: '错误',
    success: '成功',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    back: '返回',
    next: '下一步',
    submit: '提交',
    reset: '重置',
    close: '关闭',
    confirm: '确认',
    cancel: '取消',
    yes: '是',
    no: '否',
    ok: '确定',

    // 导航
    allTools: '所有工具',
    aboutUs: '关于我们',
    contact: '联系我们',
    profile: '个人资料',
    favorites: '收藏夹',
    settings: '设置',

    // 首页
    heroTitle: '发现AI语音工具',
    heroSubtitle: '找到适合您需求的语音工具',
    featuredTools: '精选工具',
    popularCategories: '热门分类',
    latestTools: '最新工具',
    newsletterTitle: '保持更新',
    newsletterSubtitle: '订阅我们的新闻通讯以获取最新更新',
    subscribe: '订阅',

    // 工具页面
    searchPlaceholder: '搜索工具...',
    categoryLabel: '分类',
    priceLabel: '价格',
    ratingLabel: '评分',
    sortBy: '排序方式',
    noResults: '未找到结果',
    addToFavorites: '添加到收藏夹',
    removeFromFavorites: '从收藏夹移除',
    free: '免费',
    paid: '付费',
    low: '低价',
    medium: '中价',
    high: '高价',

    // 关于页面
    aboutTitle: '关于RecallLook',
    aboutSubtitle: '您值得信赖的AI语音工具来源',
    ourStory: '我们的故事',
    ourMission: '我们的使命',
    ourTeam: '我们的团队',
    contactUs: '联系我们',
    name: '姓名',
    email: '邮箱',
    message: '消息',
    send: '发送',

    // 表单验证
    required: '此字段为必填项',
    invalidEmail: '请输入有效的邮箱地址',
    invalidPassword: '密码长度至少为8个字符',
    passwordMismatch: '两次输入的密码不一致',
    acceptTerms: '请接受服务条款',

    // 错误消息
    networkError: '网络错误,请重试',
    serverError: '服务器错误,请稍后重试',
    invalidCredentials: '邮箱或密码错误',
    emailExists: '邮箱已存在',
    invalidToken: '无效或过期的令牌',
    unauthorized: '未授权访问'
  }
};
