const languages = {
  en: {
    home: "Home",
    allTools: "All Tools",
    about: "About",
    login: "Login",
    signup: "Sign Up",
    heroTitle: "Your AI Voice Tools Directory",
    heroDesc: "Discover, compare, and choose the perfect voice tools for your needs",
    searchPlaceholder: "Search for AI voice tools...",
    category: "Category:",
    allCategories: "All Categories",
    priceRange: "Price Range:",
    allPrices: "All Prices",
    rating: "Rating:",
    allRatings: "All Ratings",
    featuredTools: "Featured Tools",
    featuredDesc: "Explore our handpicked selection of the best AI voice tools",
    newsletterTitle: "Subscribe to AI Voice Tools Updates",
    newsletterDesc: "Stay updated with the latest AI voice tools and industry news",
    newsletterPlaceholder: "Enter your email address",
    subscribe: "Subscribe",
    aboutTitle: "About RecallLook",
    aboutDesc: "Your trusted source for AI voice tools and resources",
    ourStory: "Our Story",
    storyContent: "Founded in 2024, RecallLook emerged from a simple observation: the AI voice technology landscape was growing rapidly, but finding the right tools was becoming increasingly challenging. Our mission is to simplify this process by providing a comprehensive directory of AI voice tools, complete with detailed reviews and user feedback.",
    ourMission: "Our Mission",
    missionContent: "At RecallLook, we're committed to helping users discover and evaluate AI voice tools that best suit their needs. We curate and review tools across various categories, from speech synthesis to voice cloning, ensuring our users have access to the most reliable and effective solutions in the market.",
    ourTeam: "Our Team",
    ceo: "CEO & Founder",
    cto: "Chief Technology Officer",
    contentLead: "Content Lead",
    contactUs: "Contact Us",
    name: "Name",
    email: "Email",
    message: "Message",
    sendMessage: "Send Message"
  },
  zh: {
    home: "首页",
    allTools: "所有工具",
    about: "关于我们",
    login: "登录",
    signup: "注册",
    heroTitle: "AI语音工具目录",
    heroDesc: "发现、比较并选择最适合您需求的语音工具",
    searchPlaceholder: "搜索AI语音工具...",
    category: "类别:",
    allCategories: "所有类别",
    priceRange: "价格范围:",
    allPrices: "所有价格",
    rating: "评分:",
    allRatings: "所有评分",
    featuredTools: "精选工具",
    featuredDesc: "探索我们精心挑选的最佳AI语音工具",
    newsletterTitle: "订阅AI语音工具更新",
    newsletterDesc: "及时了解最新的AI语音工具和行业新闻",
    newsletterPlaceholder: "输入您的邮箱地址",
    subscribe: "订阅",
    aboutTitle: "关于 RecallLook",
    aboutDesc: "您值得信赖的AI语音工具和资源平台",
    ourStory: "我们的故事",
    storyContent: "RecallLook 成立于2024年，源于一个简单的观察：AI语音技术领域正在快速发展，但找到合适的工具变得越来越具有挑战性。我们的使命是通过提供全面的AI语音工具目录，包括详细的评论和用户反馈，来简化这个过程。",
    ourMission: "我们的使命",
    missionContent: "在 RecallLook，我们致力于帮助用户发现和评估最适合他们需求的AI语音工具。我们收集和审查各个类别的工具，从语音合成到声音克隆，确保我们的用户能够获得市场上最可靠和有效的解决方案。",
    ourTeam: "我们的团队",
    ceo: "首席执行官兼创始人",
    cto: "首席技术官",
    contentLead: "内容主管",
    contactUs: "联系我们",
    name: "姓名",
    email: "电子邮箱",
    message: "留言",
    sendMessage: "发送消息"
  }
}; 
